### PR TITLE
Would it be useful to install man pages?

### PR DESCRIPTION
**Pull request by nochiel**
It might be useful to also install man pages. I found them handy when ssh'ing into the VPS.

### CODE REVIEW

**Comment by ChristopherA** [comment]
@icculp could you also take a look at this PR when you test the other?

**Review by icculp — APPROVED** [review]
Tested StandUp.sh in Debian 9 and LinodeStandUp.sh as a stackscript in Debian 10. Man pages working in both :-)

**Review by ChristopherA — APPROVED** [review]

**Comment by ChristopherA** [comment]
The problem is the commits from @nochiel are not signed. There is some GitHub fu to do this that I always have to look up, but sometimes it is just easier to just resubmit.

**Comment by nochiel** [comment]
I'll sign and update the PR.
--
Sincerely
Nicholas Ochiel

**Comment by ChristopherA** [comment]
@nochiel Github is still reporting that https://github.com/BlockchainCommons/Bitcoin-Standup-Scripts/pull/19/commits/f38940941ad010f8ababf3eecf2009bf55a9362e is not signed

**Pull request merged**
