### PR TITLE
Add CypherpunkPay.

### PR DESCRIPTION
**Pull request by nochiel**

### CODE REVIEW

**Comment by nochiel** [comment]
@icculp If you have time, please could you review this?

**Comment by shannona** [comment]
Committing to Debian 10 is not necessarily a bad thing. Debian 9 is pretty long-in-the-tooth. (Will look in more depth at everything soon.)

**Comment by shannona** [comment]
I've in fact pushed the scripts over to Debian 11 as their default, so the versioning should be fine.

Apologies for this sitting for a bit, I was doing other updates. I'm now looking over this, with the hope of fully integrating it next week.

**Comment by shannona** [comment]
(That merge was to support changes to Tor ports for bitcoin services, per Peter.

**Comment by shannona** [comment]
Sure thing! Just a few more iterations and we should be able to merge.

**Comment by shannona** [comment]
Testing of Stackscript with cypherpunkpay turned off: works fine (that's the default setup).

However I haven't yet gotten it to successfully install cypherpunkpay, apparently because the USE_CYPHERPUNKPAY variable isn't coming through? I need to investigate that more and will continue in the morning.

**Pull request merged**
